<html>
@include('../partials/_head')
<body>
@include('../partials/_nav-public')
@include('../partials/_flashmessages')
@yield('content')
@include('../partials/_basicjs')
@yield('customjs')
</body>
@include('../partials/_footer-public')
</html>